import { Directive,ElementRef,Input } from '@angular/core';

@Directive({
  selector: '[appAllNationalitiesIS]'
})
export class AllNationalitiesIcelandicDirective {
  constructor(private el: ElementRef) {
    const parent = this.el.nativeElement;
    parent.innerHTML = `
    <option value="Afghanistan">Afganistan</option>
    <option value="Albania">Albanía</option>
    <option value="Algeria">Alsír</option>
    <option value="American Samoa">Ameríska Samoa</option>
    <option value="Andorra">Andorra</option>
    <option value="Angola">Angóla</option>
    <option value="Anguilla">Angvilla</option>
    <option value="Antigua and Barbuda">Antígva og Barbúda</option>
    <option value="Argentina">Argentína</option>
    <option value="Armenia">Armenía</option>
    <option value="Aruba">Arúba</option>
    <option value="Austria">Austurríki</option>
    <option value="Azerbaijan">Aserbaídsjan</option>
    <option value="Åland Islands">Álandseyjar</option>
    <option value="Australia">Ástralía</option>
    <option value="Bahamas">Bahamaeyjar</option>
    <option value="United States">Bandaríkin</option>
    <option value="United States Minor Outlying Islands">Smáeyjar Bandaríkjanna</option>
    <option value="Bangladesh">Bangladess</option>
    <option value="Barbados">Barbados</option>
    <option value="Bahrain">Barein</option>
    <option value="Belarus">Hvíta-Rússland</option>
    <option value="Belgium">Belgía</option>
    <option value="Belize">Belís</option>
    <option value="Benin">Benín</option>
    <option value="Bermuda">Bermúdaeyjar</option>
    <option value="Bonaire, Sint Eustatius and Saba">Bonaire, Sankti Estatíusey og Saba</option>
    <option value="Bosnia and Herzegovina">Bosnía og Hersegóvína</option>
    <option value="Botswana">Botsvana</option>
    <option value="Bouvet Island">Bouveteyja</option>
    <option value="Bolivia">Bólivía</option>
    <option value="Brazil">Brasilía</option>
    <option value="British Indian Ocean Territory">Bresku Indlandshafseyjar</option>
    <option value="United Kingdom">Bretland</option>
    <option value="Brunei Darussalam">Brúnei</option>
    <option value="Bulgaria">Búlgaría</option>
    <option value="Burkina Faso">Búrkína Fasó</option>
    <option value="Burundi">Búrúndí</option>
    <option value="Bhutan">Bútan</option>
    <option value="Cape Verde">Grænhöfðaeyjar</option>
    <option value="Cayman Islands">Caymaneyjar</option>
    <option value="Chad">Tsjad</option>
    <option value="Chile">Chile</option>
    <option value="Cocos (Keeling) Islands">Kókoseyjar</option>
    <option value="Colombia">Kólumbía</option>
    <option value="Cook Islands">Cookseyjar</option>
    <option value="Costa Rica">Kostaríka</option>
    <option value="Côte d'Ivoire">Fílabeinsströndin</option>
    <option value="Curaçao">Curacao</option>
    <option value="Denmark">Danmörk</option>
    <option value="Djibouti">Djíbútí</option>
    <option value="Dominica">Dóminíka</option>
    <option value="Dominican Republic">Dóminíska lýðveldið</option>
    <option value="Egypt">Egyptaland</option>
    <option value="Estonia">Eistland</option>
    <option value="Ecuador">Ekvador</option>
    <option value="El Salvador">El Salvador</option>
    <option value="Eritrea">Erítrea</option>
    <option value="Ethiopia">Eþíópía</option>
    <option value="Falkland Islands">Falklandseyjar</option>
    <option value="Fiji">Fídjieyjar</option>
    <option value="Philippines">Filippseyjar</option>
    <option value="Finland">Finnland</option>
    <option value="France">Frakkland</option>
    <option value="French Guiana">Franska Gvæjana</option>
    <option value="French Polynesia">Franska Pólýnesía</option>
    <option value="French Southern Territories">Frönsku suðlægu landsvæðin</option>
    <option value="Faroe Islands">Færeyjar</option>
    <option value="Gabon">Gabon</option>
    <option value="Gambia">Gambía</option>
    <option value="Georgia">Georgía</option>
    <option value="Ghana">Gana</option>
    <option value="Gibraltar">Gíbraltar</option>
    <option value="Guinea">Gínea</option>
    <option value="Guinea-Bissau">Gínea-Bissá</option>
    <option value="Grenada">Grenada</option>
    <option value="Greece">Grikkland</option>
    <option value="Greenland">Grænland</option>
    <option value="Guadeloupe">Gvadelúpeyjar</option>
    <option value="Guam">Gvam</option>
    <option value="Guatemala">Gvatemala</option>
    <option value="Guernsey">Guernsey</option>
    <option value="Guyana">Gvæjana</option>
    <option value="Haiti">Haítí</option>
    <option value="Heard Island and McDonald Islands">Heard og McDonaldseyjar</option>
    <option value="Netherlands">Holland</option>
    <option value="Honduras">Hondúras</option>
    <option value="Hong Kong">Hong Kong</option>
    <option value="India">Indland</option>
    <option value="Indonesia">Indónesía</option>
    <option value="Iraq">Írak</option>
    <option value="Iran">Íran</option>
    <option value="Ireland">Írland</option>
    <option value="Iceland">Ísland</option>
    <option value="Israel">Ísrael</option>
    <option value="Italy">Ítalía</option>
    <option value="Jamaica">Jamaíka</option>
    <option value="Japan">Japan</option>
    <option value="Yemen">Jemen</option>
    <option value="Jersey">Jersey</option>
    <option value="Christmas Island">Jólaeyja</option>
    <option value="U.S. Virgin Islands">Bandarísku Jómfrúaeyjar</option>
    <option value="British Virgin Islands">Bresku Jómfrúaeyjar</option>
    <option value="Jordan">Jórdanía</option>
    <option value="Cambodia">Kambódía</option>
    <option value="Cameroon">Kamerún</option>
    <option value="Canada">Kanada</option>
    <option value="Kazakhstan">Kasakstan</option>
    <option value="Qatar">Katar</option>
    <option value="Kenya">Kenía</option>
    <option value="China">Kína</option>
    <option value="Kiribati">Kíribatí</option>
    <option value="The Democratic Republic of the Congo">Austur-Kongó</option>
    <option value="Republic of the Congo">Vestur-Kongó</option>
    <option value="Comoros">Kómoreyjar</option>
    <option value="Democratic People's Republic of Korea">Norður-Kórea</option>
    <option value="Republic of Korea">Suður-Kórea</option>
    <option value="Croatia">Króatía</option>
    <option value="Kuwait">Kúveit</option>
    <option value="Cuba">Kúba</option>
    <option value="Kyrgyzstan">Kirgisistan</option>
    <option value="Cyprus">Kýpur</option>
    <option value="Laos">Laos</option>
    <option value="Lesotho">Lesótó</option>
    <option value="Latvia">Lettland</option>
    <option value="Liechtenstein">Liechtenstein</option>
    <option value="Lithuania">Litháen</option>
    <option value="Lebanon">Líbanon</option>
    <option value="Liberia">Líbería</option>
    <option value="Libya">Líbía</option>
    <option value="Luxembourg">Lúxemborg</option>
    <option value="Madagascar">Madagaskar</option>
    <option value="Macao">Makaó</option>
    <option value="North Macedonia">Norður-Makedónía</option>
    <option value="Malaysia">Malasía</option>
    <option value="Malawi">Malaví</option>
    <option value="Maldives">Maldíveyjar</option>
    <option value="Mali">Malí</option>
    <option value="Malta">Malta</option>
    <option value="Morocco">Marokkó</option>
    <option value="Marshall Islands">Marshalleyjar</option>
    <option value="Martinique">Martiník</option>
    <option value="Mayotte">Mayotte</option>
    <option value="Mauritania">Máritanía</option>
    <option value="Mauritius">Máritíus</option>
    <option value="Mexico">Mexíkó</option>
    <option value="Central African Republic">Mið-Afríkulýðveldið</option>
    <option value="Equatorial Guinea">Miðbaugs-Gínea</option>
    <option value="Micronesia">Míkrónesía</option>
    <option value="Moldova">Moldóva</option>
    <option value="Mongolia">Mongólía</option>
    <option value="Montenegro">Svartfjallaland</option>
    <option value="Montserrat">Montserrat</option>
    <option value="Monaco">Mónakó</option>
    <option value="Mozambique">Mósambík</option>
    <option value="Myanmar">Mjanmar</option>
    <option value="Isle of Man">Mön</option>
    <option value="Namibia">Namibía</option>
    <option value="Nauru">Nárú</option>
    <option value="Nepal">Nepal</option>
    <option value="Nicaragua">Níkaragva</option>
    <option value="Niue">Niue</option>
    <option value="Niger">Níger</option>
    <option value="Nigeria">Nígería</option>
    <option value="Northern Mariana Islands">Norður-Maríanaeyjar</option>
    <option value="Norway">Noregur</option>
    <option value="Norfolk Island">Norfolkeyja</option>
    <option value="New Caledonia">Nýja-Kaledónía</option>
    <option value="New Zealand">Nýja-Sjáland</option>
    <option value="Oman">Óman</option>
    <option value="Pakistan">Pakistan</option>
    <option value="Palau">Palá</option>
    <option value="Palestine">Heimastjórnarsvæði Palestínumanna</option>
    <option value="Panama">Panama</option>
    <option value="Papua New Guinea">Papúa Nýja-Gínea</option>
    <option value="Paraguay">Paragvæ</option>
    <option value="Vatican City">Páfagarður</option>
    <option value="Peru">Perú</option>
    <option value="Pitcairn Islands">Pitcairn</option>
    <option value="Portugal">Portúgal</option>
    <option value="Poland">Pólland</option>
    <option value="Puerto Rico">Púertó Ríkó</option>
    <option value="Réunion">Réunion</option>
    <option value="Romania">Rúmenía</option>
    <option value="Russia">Rússland</option>
    <option value="Rwanda">Rúanda</option>
    <option value="Solomon Islands">Salómonseyjar</option>
    <option value="United Arab Emirates">Sameinuðu arabísku furstadæmin</option>
    <option value="Samoa">Samóa</option>
    <option value="San Marino">San Marínó</option>
    <option value="Saint Barthélemy">Sankti Barthelemy</option>
    <option value="Saint Helena, Ascension and Tristan da Cunha">Sankti Helena, Ascension og Tristan da Cunha</option>
    <option value="Saint Kitts and Nevis">Sankti Kristófer og Nevis</option>
    <option value="Saint Lucia">Sankti Lúsía</option>
    <option value="Sint Maarten (Dutch Part)">Sankti Maarten (hollenski hlutinn)</option>
    <option value="Saint Martin (French Part)">Sankti Martin (franski hlutinn)</option>
    <option value="Saint Pierre and Miquelon">Sankti Pierre og Miquelon</option>
    <option value="Saint Vincent and the Grenadines">Sankti Vinsent og Grenadíneyjar</option>
    <option value="Sao Tome and Principe">Saó Tóme og Prinsípe</option>
    <option value="Saudi Arabia">Sádi-Arabía</option>
    <option value="Senegal">Senegal</option>
    <option value="Serbia">Serbía</option>
    <option value="Seychelles">Seychelles-eyjar</option>
    <option value="Singapore">Singapúr</option>
    <option value="Sierra Leone">Síerra Leóne</option>
    <option value="Slovakia">Slóvakía</option>
    <option value="Slovenia">Slóvenía</option>
    <option value="Somalia">Sómalía</option>
    <option value="Spain">Spánn</option>
    <option value="Sri Lanka">Srí Lanka</option>
    <option value="South Africa">Suður-Afríka</option>
    <option value="South Georgia and the South Sandwich Islands">Suður-Georgía og Suður-Sandvíkureyjar</option>
    <option value="Antarctica">Suðurskautslandið</option>
    <option value="South Sudan">Suður-Súdan</option>
    <option value="Sudan">Súdan</option>
    <option value="Suriname">Súrínam</option>
    <option value="Svalbard and Jan Mayen">Svalbarði og Jan Mayen</option>
    <option value="Switzerland">Sviss</option>
    <option value="Sweden">Svíþjóð</option>
    <option value="Swaziland">Svasíland</option>
    <option value="Syria">Sýrland</option>
    <option value="Tajikistan">Tadsjikistan</option>
    <option value="Taiwan">Taívan</option>
    <option value="Tanzania">Tansanía</option>
    <option value="Czechia">Tékkland</option>
    <option value="Thailand">Taíland</option>
    <option value="Timor-Leste">Austur-Tímor</option>
    <option value="Tokelau">Tókelá</option>
    <option value="Tonga">Tonga</option>
    <option value="Togo">Tógó</option>
    <option value="Trinidad and Tobago">Trínidad og Tóbagó</option>
    <option value="Turks and Caicos Islands">Turks- og Caicoseyjar</option>
    <option value="Tunisia">Túnis</option>
    <option value="Turkmenistan">Túrkmenistan</option>
    <option value="Tuvalu">Túvalú</option>
    <option value="Turkey">Tyrkland</option>
    <option value="Hungary">Ungverjaland</option>
    <option value="Uruguay">Úrúgvæ</option>
    <option value="Uganda">Úganda</option>
    <option value="Ukraine">Úkraína</option>
    <option value="Uzbekistan">Úsbekistan</option>
    <option value="Vanuatu">Vanúatú</option>
    <option value="Venezuela">Venesúela</option>
    <option value="Western Sahara">Vestur-Sahara</option>
    <option value="Vietnam">Víetnam</option>
    <option value="Wallis and Futuna">Wallis- og Fútúnaeyjar</option>
    <option value="Zambia">Sambía</option>
    <option value="Zimbabwe">Zimbabwe</option>
    <option value="Germany">Þýskaland</option>
    <option value="Netherlands Antilles">Hollensku Antillur</option>`;
  }
}
